[[function]]
name = "sum"
ret = "i32"
args = ["i32","i32"]

[[function]]
name = "scat"
ret = "string"
args = ["string", "string"]

[[function]]
name = "toString_int"
ret = "string"
args = ["i32"]

[[function]]
name = "toString_bool"
ret = "string"
args = ["i1"]

[[function]]
name = "toString_float"
ret = "string"
args = ["float"]

[[function]]
name = "echo"
ret = "void"
args = ["string"]

[[function]]
name = "test"
ret = "void"
args = ["i1"]